version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-3.5-turbo}
      - USE_OPENAI=${USE_OPENAI:-true}
    volumes:
      - ./app:/app/app
    restart: unless-stopped

